name: Approval Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  approve:
    if: github.event.label.name == 'approve'
    runs-on: ubuntu-latest
    steps:
      - name: Approve Page
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          issue_body=$(echo "${{ github.event.issue.body }}" | base64 --decode)
          page_data=$(echo "$issue_body" | jq -r '.page_data')
          echo "Page approved"
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"state":"closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
