name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        email_key: ['EMAIL_1', 'EMAIL_2'] # Add more email keys as needed
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Send Email
      env:
        ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
        ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
      run: |
        python send_email.py ${{ matrix.email_key }}
